version: "3"
services:
  api:
    image: 637423548813.dkr.ecr.eu-west-3.amazonaws.com/beable-materiais:api
    mem_limit: 512
    hostname: api
    environment:
      - CONNECTION_STRING=#CONNECTION_STRING
  nginx:
    image: 637423548813.dkr.ecr.eu-west-3.amazonaws.com/beable-materiais:nginx
    mem_limit: 256
    hostname: nginx
    ports:
      - "443:443"
  client:
    image: 637423548813.dkr.ecr.eu-west-3.amazonaws.com/beable-materiais:client
    mem_limit: 256
    hostname: client