version: "3"
services:
  api:
    image: mateusgpedro/beable-materiais
    mem_limit: 512,
    hostname: api,
    environment:
      - CONNECTION_STRING=#CONNECTION_STRING
  nginx:
    image: mateusgpedro/beable-nginx,
    mem_limit: 256,
    hostname: nginx,
    ports:
      - "80:80"
  client:
    image: mateusgpedro/beable-client,
    mem_limit: 256,
    hostname: client,