version: "3"
services:
  api:
    image: 637423548813.dkr.ecr.eu-west-3.amazonaws.com/beable-materiais:api
    mem_limit: 256m
    hostname: api
    environment:
      - CONNECTION_STRING=User ID=superuser;Password=Able2020#;Host=beable-materiais.cnkw6ogoazko.eu-west-3.rds.amazonaws.com;Port=5432;Database=beable-materiais;
      - ASPNETCORE_URLS=http://+:5000

    ports: 
      - "5000:5000"  
  nginx:
    image: 637423548813.dkr.ecr.eu-west-3.amazonaws.com/beable-materiais:nginx
    mem_limit: 256m
    hostname: nginx
    ports:
      - "80:80"
  client:
    image: 637423548813.dkr.ecr.eu-west-3.amazonaws.com/beable-materiais:client
    mem_limit: 256m
    hostname: client