version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./ProjetoMateriasAble/ProjetoMateriasAble
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development  

    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/bin
      - /app/obj
      - /app/ProjetoMateriasAble/bin
      - /app/ProjetoMateriasAble/obj
      - ~/.aspnet/https:/https:ro
  # nginx:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - "80:80"
  # client:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./frontend