name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        run: |
          docker build -t beable-materiais/client ./frontend
          docker build -t beable-materiais/api ./ProjetoMateriasAble/ProjetoMateriasAble
          docker build -t beable-materiais/nginx ./nginx

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_PUSH }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_PUSH }}
          aws-region: eu-west-3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag images to ECR URI
        env:
          AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
        run: |
          docker tag beable-materiais/client $AWS_ECR_URI:client
          docker tag beable-materiais/api $AWS_ECR_URI:api
          docker tag beable-materiais/nginx $AWS_ECR_URI:nginx

      - name: Push images to ECR URI
        env:
          AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
        run: |
          docker push $AWS_ECR_URI:client
          docker push $AWS_ECR_URI:api
          docker push $AWS_ECR_URI:nginx

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: beable-materiais
          environment_name: Beable-materiais-env
          existing_bucket_name: elasticbeanstalk-eu-west-3-637423548813
          region: eu-west-3
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
